### ISSUE TITLE
 hotspot.status is not a function

### ISSUE THREAD

**Issue by hmharsh** [luigiplr/node-hotspot#2]
copy the given code and after npm install run same code showing error

TypeError: hotspot.status is not a function
    at Object.<anonymous> (F:\DATA\Study\node\hotspot\hotspot.js:26:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

**Comment by luigiplr** [comment]
Hmm try `hotspot.stats()`

I may have forgotten to update the readme, sorry!

**Comment by hmharsh** [comment]
Thank you so much @luigiplr  it is working now !!
