### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by tobeorla** [luigiplr/node-hotspot#5]
**O.S:** Windows 10
**Code:**
```js
lookForConnections() {
                hotspot.stats({
                    ssid: 'test',
                    password: '12345678',
                    force: true, // (optional)  if hosting a network already turn it off and run ours.
                })
                    .then(function(status) {
                        console.log(status) //status contains clients object and state
                    });
            }
```
**Error:**
```js
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:111:22
From previous event:
    at C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:106:52
From previous event:
    at Object.getCompatible (C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:105:16)
    at C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:86:168
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
From previous event:
    at C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:85:30
From previous event:
    at Object.getStatus (C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\utils\windows.js:84:16)
    at Object.stats (C:\Users\me\Desktop\wifi\dongle-setup\node_modules\node-hotspot\build\hotspot.js:52:57)
    at VueComponent.lookForConnections (eval at <anonymous> (http://localhost:9080/renderer.js:794:1), <anonymous>:29:73)
    at boundFn (eval at <anonymous> (http://localhost:9080/renderer.js:724:1), <anonymous>:166:12)
```

**Comment by luigiplr** [comment]
Possibly related to https://github.com/luigiplr/node-hotspot/issues/7 ?

**Comment by tobeorla** [comment]
It is, i'm closing this issue as i made a "hack" to make it work for my locale:
https://github.com/tobeorla/node-hotspot/commit/6fcffd406542965183bbe9804761165906531b47
